### ISSUE TITLE
我是否能在非imgui的opengl上下文中使用它

### ISSUE THREAD

**Issue by baier233** [rcszc/OGL-ImGui-BloomEXT#1]

**Comment by rcszc** [comment]
不能, 因为辉光处理着色器管线与图形API密切相关.

**Comment by rcszc** [comment]
不能, 因为辉光处理着色器管线与图形API密切相关, 它的原理是: 你的ImGui界面绘制完成后图像不输出到屏幕, 而是输出到后期处理的着色器管线, 经过过滤、模糊、混合处理后再输出到屏幕.

**Comment by baier233** [comment]
如果我把我要绘制的内容输出到我自己创建的FBO上，我是否能够使用这个辉光处理呢？

**Comment by rcszc** [comment]
这个是高度定制封装的调用, 你如果都渲染到自己的FBO了那不如自己实现了与这个扩展没有关系了, 你可以用readme中的架构图尝试自己在其他API实现, 目前这个仓库的扩展只能是OpenGL3.
